Fletching fixes
CurtisGreen/rs-clicker pull request #7
Opened 2020-12-12 19:26 UTC by CurtisGreen

Minor changes / fixes based on comments on previous pull request.

Note: I noticed a bug where sometimes stacking a weapon in your inventory (by fletching or unequipping a weapon of which the same type already exists in your inventory) will result in the item count not displaying. The data is saved, so if you refresh it will come back and function normally, but there is something wrong with the initial render.

Due to not being able to consistently reproduce it I'm assuming it's a timing issue that might be resolved by making "create sprite" async

2020-12-12 22:19 UTC, EthanVieira requested changes
These changes should be merged into either https://github.com/EthanVieira/rs-clicker/pull/42 or https://github.com/EthanVieira/rs-clicker/pull/43

2020-12-13 00:10 UTC, CurtisGreen commented
> These changes should be merged into either [EthanVieira#42](https://github.com/EthanVieira/rs-clicker/pull/42) or [EthanVieira#43](https://github.com/EthanVieira/rs-clicker/pull/43)

I did a lot of changes on this fork so that's not gonna work. You can check out the fat diff here:   
https://github.com/EthanVieira/rs-clicker/compare/master...CurtisGreen:master

2020-12-13 19:15 UTC, CurtisGreen commented
It would probably be good to read the descriptions of the PRs I merged into this fork so you get an idea of what I did. The biggest change was https://github.com/CurtisGreen/rs-clicker/pull/4. I basically added get/set functions to the `characterData` object so I could add better error checking and track down issues easier. Almost every file uses character data so the diff is naturally large even though it's a lot of 1 line changes. I found/prevented a lot of bugs with this change so I'm pretty happy with it

2020-12-13 20:40 UTC, EthanVieira commented
https://github.com/EthanVieira/rs-clicker/pull/44 - can you make sure my handling of merge conflicts is fine?

2020-12-13 21:56 UTC, merged